apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-clusterrole
rules:
  - apiGroups: [""]
    resources: 
      - services
      - secrets
      - configmaps
    verbs: 
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources: 
      - ingresses
      - ingressclasses
    verbs: 
      - list
      - watch
  - apiGroups: ["discovery.k8s.io"]
    resources: 
      - endpointslices
    verbs: 
      - list
      - watch
