# Common Labels
labels:
  app: "zuul"
  group: "gateway"

serviceAccount: zuul
namespace: egov  

# Init Containers Configs
initContainers: 
  extraInitContainers: |
    - name: "zuul-kubernetes-discovery"
      image: "{{ .Values.global.containerRegistry }}/zuul-kubernetes-discovery:2-master-91c9795"      
      env: 
      - name: "OUTPUT_FILE_PATH"
        value: "/etc/zuul/routes.properties" 
      - name: "NAMESPACE"
        value: "egov"         
      volumeMounts:
      - name: zuul-routes
        mountPath: /etc/zuul

extraVolumes: |
  - name: zuul-routes
    emptyDir: {}  

extraVolumeMounts: |     
  - name: zuul-routes
    mountPath: "/etc/zuul"

# Container Configs
image:
  repository: "zuul"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/health"
  readinessProbePath: "/health"
custom-filter-property: "false"
posthook-config: ""
prehook-config: ""
heap: "-Xmx640m -Xms512m"
memory_limits: 768Mi
appType: "java-spring"
tracing-enabled: true
server-tomcat-max-threads: "350"
server-tomcat-max-connections: "1500"
java-args: ""
egov-open-endpoints-whitelist: "/user/oauth/token,/user-otp/v1/_send,/otp/v1/_validate,/user/citizen/_create,/localization/messages,/localization/messages/v1/_search,/user/password/nologin/_update,/tenant/v1/tenant/_search,/egov-location/boundarys,/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName,/egov-location/boundarys/getLocationByLocationName,/egov-mdms-service/v1/_search,/egov-location/location/v11/geography/_search,/filestore/v1/files/url,/pt-calculator-v2/billing-slab/_search,/egov-searcher/property-services/propertyopensearch/_get,/edcr/rest/dcr/downloadfile"  
egov-mixed-mode-endpoints-whitelist: "/filestore/v1/files/id,/filestore/v1/files,/filestore/v1/files/tag,/user/_search,/access/v1/actions/mdms/_get,/tl-services/v1/_search,/tl-services/v1/BPAREG/_search,/tl-services/v1/BPAREG/_create,/tl-services/v1/BPAREG/_update,/tl-calculator/v1/BPAREG/_getbill,/bpa-services/bpa/appl/_search,/edcr/rest/dcr/scrutinize,/edcr/rest/dcr/scrutinydetails"
tattva-mixed-mode-endpoints-whitelist: "/deonar-v1/animal/slaughter_save,/deonar-v1/assign/animal,/deonar-v1/collection/fee/_save,/deonar-v1/collection/fee/entry/_get,/deonar-v1/collection/fee/parking/_get,/deonar-v1/collection/fee/stable/_get,/deonar-v1/collection/fee/trading/_get,/deonar-v1/collection/fee/washing/_get,/deonar-v1/collection/fee/weighing/_get,/deonar-v1/common/get_vehicles,/deonar-v1/gate/pass/_search,/deonar-v1/get/animalList/dawanwala,/deonar-v1/get/penalties,/deonar-v1/get/removal_list,/deonar-v1/get/shopkeepers,/deonar-v1/get/slaughter_list,/deonar-v1/get/trading_list,/deonar-v1/get/vehicles,/deonar-v1/inspection/_search,/deonar-v1/inspection/save,/deonar-v1/penalty_save,/deonar-v1/securityCheck/_save,/deonar-v1/securityCheck/_search,/deonar-v1/stakeholder/_get,/deonar-v1/vehicleParking/_parkingFee,/deonar-v1/vehicleParking/_save,/deonar-v1/vehicleParking/_saveMonthlyParkingFee,/deonar-v1/vehicleParking/_search,/deonar-v1/vehicleParking/_searchVehicleMonthlyParkingFee,/deonar-v1/vehicleParking/_VehicleWashingFee,/deonar-v1/common/_get,/deonar-v1/get/stabling/_list,/deonar-v1/get/removal/_list,/deonar-v1/get/trading/_list,/deonar-v1/get/weighing/_list,/deonar-v1/get/slaughter/_list,/deonar-v1/get/animalList/_dawanwala,/deonar-v1/get/animalList/_helkari,/deonar-v1animal/slaughter/_save,/deonar-v1/collection/fee/removal/_get,/deonar-v1/collection/fee/slaughter/_get,/deonar-v1/gatePass/_search,/deonar-v1/gatePass/_save,/deonar-v1/penalty/list/_get,/deonar-v1/penalty/_save,/deonar-v1/get/_penalties,/deonar-v1/vehicleParking/_parkedInVehicle,/deonar-v1//animal/slaughter/_save,/deonar-v1/animal/slaughter/_save,/deonar-v1/animal/slaughter/_shifts,/deonar-v1/slaughter/list/_booking,/deonar-v1/animal/slaughter/_booking,/deonar-v1/animal/slaughter/_export,/deonar-v1/animal/slaughterList/_normal,/deonar-v1/animal/slaughterList/_emergency,/deonar-v1/inspection/submit,/deonar-v1/stakeholders/_save,/deonar-v1/vehicleWashing/_save,/deonar-v1/vehicleWashing/_washInVehicle,/deonar-v1/collectionfee/slaughterunitfee/_save,/deonar-v1/collectionfee/_save,/deonar-v1/stakeholders/_getAll,/deonar-v1/get/stabling/list/_collection,/deonar-v1/get/entry/list/_collection,/deonar-v1/vehicleWashing/_VehicleWashingFee,/deonar-v1/get/removal/list/_collection,/deonar-v1/get/slaughter/list/_collection,/deonar-v1/citizenGatePass/_get,/deonar-v1/citizenGatePass/_save,/deonar-v1/stakeholders/_assigned,/deonar-v1/securityCheck/_update,/deonar-v1/gatePass/_get,/deonar-v1/collectionfee/_get,/deonar-v1/collectionfee/slaughterunitfee/_get,/deonar-v1/collection/fee/penalty/_get,/bmc-service-v1/common/_get,/bmc-service-v1/application/_save,/bmc-service-v1/application/v1/_rendomize,/bmc-service-v1/application/v1/_search,/bmc-service-v1/bank/_get,/bmc-service-v1/common/_get/_banks,/bmc-service-v1/scheme/_search,/bmc-service-v1/user/_get,/bmc-service-v1/user/_save,/bmc-service-v1/verifier/_getapplications,/bmc-service-v1/Employee/workflow/_transit,/bmc-service-v1/application/_getcount,/bmc-service-v1/application/_status,/bmc-service-v1/user/qualification/_save,/bmc-service-v1/user/bank/_save,/bmc-service-v1/user/document/_save,/bmc-service-v1/user/remove/_document,/bmc-service-v1/application/_getAll,/bmc-service-v1/common/boundary/_get,/bmc-service-v1/application/boundary/_save,/bmc-service-v1/application/common/_save,/bmc-service-v1/common/master/_get"
eventlog-enabled: "false"
eventlog-topic: "zuul-event-log"
eventlog-urls-whitelist: ""
home-isolation-chatbot-router-enabled: false

# Additional Container Envs
env: |
  - name: URL_LISTS
    value: "/pt-services-v2/property/_create:http://rainmaker-custom-service:8000/customization/protected/punjab-pt/property/_create|/pt-services-v2/property/_update:http://rainmaker-custom-service:8000/customization/protected/punjab-pt/property/_update|/pt-calculator-v2/propertytax/_estimate:http://rainmaker-custom-service:8000/customization/protected/punjab-pt/pt-calculator-v2/_estimate"
  - name: CUSTOM_FILTER_PROPERTY
    value: {{ index .Values "custom-filter-property" | quote }}
  - name: CUSTOM_FILTER_POSTHOOKS
    value: "true"
  - name: CUSTOM_FILTER_PREHOOKS
    value: "true"
  - name: URL_POSTHOOK_LISTS
    value: {{ index .Values "posthook-config" | quote }}
  - name: URL_PREHOOK_LISTS        
    value: {{ index .Values "prehook-config" | quote }}
  - name: ZUUL_ROUTES_TL_CALCULATOR_URL
    value: http://tl-calculator:8080/                                  
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-api-gateway
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: EGOV_CUSTOM_ASYNC_FILTER_TOPIC
    value: res-custom-filter
  - name: EGOV_OPEN_ENDPOINTS_WHITELIST
    value: {{ index .Values "egov-open-endpoints-whitelist" | quote }}  
  - name: EGOV_MIXED_MODE_ENDPOINTS_WHITELIST
    value: {{ index .Values "egov-mixed-mode-endpoints-whitelist" | quote }} 
  - name: TATTVA-MIXED-MODE-ENDPOINTS-WHITELIST
    value: {{ index .Values "tattva-mixed-mode-endpoints-whitelist" | quote }}  
  - name: EVENTLOG_ENABLED
    value: {{ index .Values "eventlog-enabled" | quote }}   
  - name: EVENTLOG_TOPIC
    value: {{ index .Values "eventlog-topic" | quote }}   
  - name: EVENTLOG_URLS_WHITELIST
    value: {{ index .Values "eventlog-whitelist" | quote }}   
  - name: EGOV_AUTHORIZE_ACCESS_CONTROL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-accesscontrol
  - name: EGOV_AUTH_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user     
  - name: ZUUL_HOST_CONNECT_TIMEOUT_MILLIS
    value: "20000"
  - name: ZUUL_HOST_SOCKET_TIMEOUT_MILLIS
    value: "60000"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: EGOV_STATELEVEL_TENANT
    valueFrom:
      configMapKeyRef:
        key: egov-state-level-tenant-id
        name: egov-config    
  - name: ZUUL_ROUTES_FILEPATH
    value: "file:/etc/zuul/routes.properties"   
  {{- if index .Values "home-isolation-chatbot-router-enabled" }}
  - name: HOME_ISOLATION_CHATBOT_ROUTER_ENABLED
    value: {{ index .Values "home-isolation-chatbot-router-enabled" | quote }}  
  - name: CHATBOT_CONTEXT_PATH
    value: "/whatsapp-webhook"
  - name: EGOV_USER_ISOLATION_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-enc
  - name: HOME_ISOLATION_CHATBOT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: home-isolation-chatbot
  {{- end }}
