# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # NUGP Internal -------------------------------------------------------------------------------------------------------------        
        - path_regex: environments/dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/mrk-ac28e4c2b98f438cbdd73c2fa56fe485'  

          