# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # NUGP Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/ci\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/bfd16607-8f68-4801-b0cb-549e2f72fdf4'

        - path_regex: environments/dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/bfd16607-8f68-4801-b0cb-549e2f72fdf4'  

        - path_regex: environments/uat\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/bfd16607-8f68-4801-b0cb-549e2f72fdf4'

        - path_regex: environments/prod\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/bfd16607-8f68-4801-b0cb-549e2f72fdf4'  
        
        

          