# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # NUGP Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/ci\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/mrk-ac28e4c2b98f438cbdd73c2fa56fe485'

        - path_regex: environments/dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/mrk-ac28e4c2b98f438cbdd73c2fa56fe485'  

        - path_regex: environments/uat\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/mrk-ac28e4c2b98f438cbdd73c2fa56fe485'

        - path_regex: environments/prod\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:713626956440:key/mrk-ac28e4c2b98f438cbdd73c2fa56fe485'
          
                    #kms: 'arn:aws:kms:ap-south-1:011528278089:key/4530fe52-b34d-4264-8f6d-eca3a1958d6a

          # New Key arn:aws:kms:ap-south-1:713626956440:key/mrk-ac28e4c2b98f438cbdd73c2fa56fe485