        # Common Labels
        labels:
          app: "deonar-v1"
          group: "rainmaker"

        # Ingress Configs
        ingress:
          enabled: true
          zuul: true
          context: "deonar-v1"

        # Init Containers Configs
        initContainers:
          dbMigration:
            enabled: true
            schemaTable: "deonar-v1_schema"
            image:
              repository: "deonar-v1-db"

        # Container Configs
        image:
          repository: "deonar-v1"
        replicas: "1"
        memory_limits: "512Mi"
        healthChecks:
          enabled: false
          livenessProbePath: "/deonar-v1/health"
          readinessProbePath: "/deonar-v1/health"
        appType: "java-spring"
        tracing-enabled: true
        heap: "-Xmx192m -Xms192m"
        java-args: "-Dspring.profiles.active=monitoring"
        notification-sms-enabled: ""
        employee-allowed-search-params: ""
        citizen-allowed-search-params: ""
        env: |
          - name: EGOV_IDGEN_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-idgen
          - name: EGOV_MDMS_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-mdms-service
          - name: EGOV_USER_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-user
          - name: EGOV_LOCATION_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-location
          - name: EGOV_LOCALIZATION_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-localization
          - name: EGOV_WORKFLOW_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-workflow-v2              
          - name: EGOV_CALCULATION_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: deonar-v1
          {{- if index .Values.global "tracer-errors-provideexceptionindetails" }}
          - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
            valueFrom:
              configMapKeyRef:
                name: egov-config
                key: tracer-errors-provideexceptionindetails
          {{- end }}
          - name: DEONAR_KAFKA_ARRIVAL_TOPIC
            value: "topic_deonar_arrival"
          - name: DEONAR_KAFKA_UPDATE_TOPIC
            value: "update-deonar-application"
          - name: DEONAR_KAFKA_INSPECTION_TOPIC
            value: "save-inspection-details"
          - name: DEONAR_KAFKA_ANIMAL_ASSIGNMENT_TOPIC
            value: "save-animal-assignment"
          - name: DEONAR_KAFKA_ANIMAL_REMOVAL_TOPIC
            value: "save-animal-removal"
          - name: DEONAR_KAFKA_VEHICLE_PARKING_TOPIC
            value: "save-vehicle-parking"
          - name: DEONAR_KAFKA_SAVE_FEE_TOPIC
            value: "topic_deonar_savefee"
          - name: DEONAR_KAFKA_SAVE_MONTHLY_PARKING_FEE_TOPIC
            value: "topic-monthly-parking-savefee"
          - name: DEONAR_KAFKA_SAVE_GATE_PASS_DETAILS
            value: "save-gate-pass-details"
          - name: DEONAR_KAFKA_SAVE_PENALTY
            value: "topic_deonar_savepenalty"
          - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
            value: "org.apache.kafka.common.serialization.StringSerializer"
          - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
            value: "org.springframework.kafka.support.serializer.JsonSerializer"
          - name: JAVA_OPTS
            value: {{ .Values.heap | quote }}
          - name: JAVA_ARGS
            value: {{ .Values.javaArgs | quote }}
          - name: SERVER_PORT
            value: "8080"
          - name: EGOV_IDGEN_PTID_FORMAT
            value: "PT-[city]-[SEQ_EG_PT_PTID]"
          - name: EGOV_IDGEN_ASSM_FORMAT
            value: "AS-[cy:YYYY-MM-dd]-[SEQ_EG_PT_ASSM]"
          - name: NOTIFICATION_URL
            valueFrom:
              configMapKeyRef:
                name: egov-config
                key: egov-services-fqdn-name
          - name: SECURITY_BASIC_ENABLED
            value: "false"
          - name: MANAGEMENT_SECURITY_ENABLED
            value: "false"
          - name: NOTIFICATION_SMS_ENABLED
            value: {{ .Values.notificationSmsEnabled | quote }}
          - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
            value: "true"
          {{- if index .Values "employee-allowed-search-params" }}
          - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
            value: {{ index .Values "employee-allowed-search-params" | quote }}
          {{- end }}
          {{- if index .Values "citizen-allowed-search-params" }}
          - name: CITIZEN_ALLOWED_SEARCH_PARAMS
            value: {{ index .Values "citizen-allowed-search-params" | quote }}
          {{- end }}
          - name: EGOV_UI_APP_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-config
                key: egov-services-fqdn-name
          - name: EGOV_USR_EVENTS_CREATE_TOPIC
            value: "persist-user-events-async"
          - name: RAZORPAY_URL
            value: "https://ifsc.razorpay.com/"
          {{- if .Values.tracingEnabled }}
          - name: TRACER_OPENTRACING_ENABLED
            value: "true"
          {{- end }}
          # Added topics as environment variables
          - name: KAFKA_TOPICS
            value: "topic_deonar_arrival:1:1,update-deonar-application:1:1,save-inspection-details:1:1,save-animal-assignment:1:1,save-animal-removal:1:1,save-vehicle-parking:1:1,topic_deonar_savefee:1:1,topic-monthly-parking-savefee:1:1,save-gate-pass-details:1:1,topic_deonar_savepenalty:1:1"

