        # Common Labels
        labels:
          app: "ebinder-v1"
          group: "rainmaker"

        # Ingress Configs
        ingress:
          enabled: true
          zuul: true
          context: "ebinder-v1"

        # Init Containers Configs
        initContainers:
          dbMigration:
            enabled: true
            schemaTable: "ebinder-v1_schema"
            image:
              repository: "ebinder-v1-db"

        # Container Configs
        image:
          repository: "ebinder-v1"
        replicas: "1"
        memory_limits: "512Mi"
        healthChecks:
          enabled: false
          livenessProbePath: "/ebinder-v1/health"
          readinessProbePath: "/ebinder-v1/health"
        appType: "java-spring"
        tracing-enabled: true
        heap: "-Xmx192m -Xms192m"
        java-args: "-Dspring.profiles.active=monitoring"
        notification-sms-enabled: ""
        employee-allowed-search-params: ""
        citizen-allowed-search-params: ""
        env: |
          - name: EGOV_IDGEN_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-idgen
          - name: EGOV_MDMS_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-mdms-service
          - name: EGOV_USER_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-user
          - name: EGOV_LOCATION_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-location
          - name: EGOV_LOCALIZATION_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-localization
          - name: EGOV_WORKFLOW_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: egov-workflow-v2              
          - name: EGOV_CALCULATION_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-service-host
                key: ebinder-v1
          {{- if index .Values.global "tracer-errors-provideexceptionindetails" }}
          - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
            valueFrom:
              configMapKeyRef:
                name: egov-config
                key: tracer-errors-provideexceptionindetails
          {{- end }}
          - name: EBINDER_KAFKA_CREATE_TOPIC
            value: "save-eBinder-application"
          - name: EBINDER_KAFKA_CELIST_TOPIC
            value: "save-eBinder-ceList"
          - name: EBINDER_KAFKA_ENQUIRY_TOPIC
            value: "save-pe-enquiry"
          - name: EBINDER_KAFKA_ENQUIRY_RECORDS_TOPIC
            value: "upsert-pe-enq-records"
          - name: EBINDER_KAFKA_ENQUIRY_PE_SUBMIT_TOPIC
            value: "save-pe-submission-report"
          - name: EBINDER_KAFKA_ENQUIRY_ADD_CE_EMPLOYEE
            value: "add-ce-employee"
          - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
            value: "org.apache.kafka.common.serialization.StringSerializer"
          - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
            value: "org.springframework.kafka.support.serializer.JsonSerializer"
          - name: JAVA_OPTS
            value: {{ .Values.heap | quote }}
          - name: JAVA_ARGS
            value: {{ .Values.javaArgs | quote }}
          - name: SERVER_PORT
            value: "8080"
          - name: EGOV_IDGEN_PTID_FORMAT
            value: "PT-[city]-[SEQ_EG_PT_PTID]"
          - name: EGOV_IDGEN_ASSM_FORMAT
            value: "AS-[cy:YYYY-MM-dd]-[SEQ_EG_PT_ASSM]"
          - name: NOTIFICATION_URL
            valueFrom:
              configMapKeyRef:
                name: egov-config
                key: egov-services-fqdn-name
          - name: SECURITY_BASIC_ENABLED
            value: "false"
          - name: MANAGEMENT_SECURITY_ENABLED
            value: "false"
          - name: NOTIFICATION_SMS_ENABLED
            value: {{ .Values.notificationSmsEnabled | quote }}
          - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
            value: "true"
          {{- if index .Values "employee-allowed-search-params" }}
          - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
            value: {{ index .Values "employee-allowed-search-params" | quote }}
          {{- end }}
          {{- if index .Values "citizen-allowed-search-params" }}
          - name: CITIZEN_ALLOWED_SEARCH_PARAMS
            value: {{ index .Values "citizen-allowed-search-params" | quote }}
          {{- end }}
          - name: EGOV_UI_APP_HOST
            valueFrom:
              configMapKeyRef:
                name: egov-config
                key: egov-services-fqdn-name
          - name: EGOV_USR_EVENTS_CREATE_TOPIC
            value: "persist-user-events-async"
          - name: RAZORPAY_URL
            value: "https://ifsc.razorpay.com/"
          {{- if .Values.tracingEnabled }}
          - name: TRACER_OPENTRACING_ENABLED
            value: "true"
          {{- end }}
          # Added topics as environment variables
          - name: KAFKA_TOPICS
            value: "save-eBinder-application:1:1,save-eBinder-ceList:1:1,save-pe-enquiry:1:1,upsert-pe-enq-records:1:1,save-pe-submission-report:1:1,add-ce-employee:1:1"

